name: CI - CD - Infra

on:
  workflow_call:
    inputs:
      tf_version:
        type: string
        required: true
      working_directory:
        type: string
        required: true
      environment:
        type: string
        required: true
      area:
        type: string
        required: true
      azure_client_id:
        type: string
      azure_subscription_id:
        type: string
      azure_tenant_id:
        type: string
      apply_changes:
        type: boolean
        default: false

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform format
        id: fmt
        run: terraform fmt -check -recursive -diff
        continue-on-error: false

      - name: Post format comment
        if: ${{ !cancelled() && github.event_name == 'pull_request' && (steps.fmt.outcome == 'success' || steps.fmt.outcome == 'failure') }}
        uses: GetTerminus/terraform-pr-commenter@93a60116ff139d4e9b92b2b61ddc15ebfbdb89c6 # v3.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_WORKSPACE: ${{ inputs.working_directory }}
        with:
          commenter_type: fmt
          commenter_input: ${{ format('{0}{1}', steps.fmt.outputs.stdout, steps.fmt.outputs.stderr) }}
          commenter_exitcode: ${{ steps.fmt.outputs.exitcode }}

      - name: Cache plugin dir
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4.1.1
        name: Setup TFLint
        with:
          tflint_version: v0.52.0
      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TFLint
        run: tflint --recursive -f compact

      - name: Checkov GitHub Action
        id: checkov
        uses: bridgecrewio/checkov-action@856690c79fbb0457e734fa140d1cf4b1bdef4cd9 # v10

  plan:
    name: Plan
    needs: validate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    outputs:
      tf_plan_name: ${{ env.TF_PLAN_NAME }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: 'Azure CLI login'
        uses: azure/login@6b2456866fc08b011acb422a92a4aa20e2c4de32 # v2.1.0
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
          allow-no-subscriptions: false

      - name: Write backend config file
        run: |
          cat > backend.tfbackend <<EOF
          resource_group_name  = "${{ env.TF_VAR_resource_group_name_tfstate }}"
          storage_account_name = "${{ env.TF_VAR_storage_account_name_tfstate }}"
          container_name       = "${{ env.TF_VAR_container_name_tfstate }}"
          key                  = "${{ inputs.area }}.tfstate"
          use_oidc             = true
          EOF
        env:
          TF_VAR_resource_group_name_tfstate: ${{ vars.TF_VAR_resource_group_name_tfstate }}
          TF_VAR_storage_account_name_tfstate: ${{ vars.TF_VAR_storage_account_name_tfstate }}
          TF_VAR_container_name_tfstate: ${{ vars.TF_VAR_container_name_tfstate }}

      - name: Terraform init
        run: terraform init -backend-config=backend.tfbackend

      - name: Post init comment
        if: ${{ !cancelled() && github.event_name == 'pull_request' && (steps.init.outcome == 'success' || steps.init.outcome == 'failure') }}
        uses: GetTerminus/terraform-pr-commenter@93a60116ff139d4e9b92b2b61ddc15ebfbdb89c6 # v3.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_WORKSPACE: ${{ inputs.working_directory }}
        with:
          commenter_type: init
          commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
          commenter_exitcode: ${{ steps.init.outputs.exitcode }}

      - name: Define workspace plan name
        run: |
          echo "TF_PLAN_NAME=${{ inputs.area }}-${{ github.run_id }}-${{ github.run_attempt }}.plan" >> "$GITHUB_ENV"

      - name: Terraform plan
        id: plan
        run: |
          set -o pipefail
          terraform plan -no-color -input=false -out=$TF_PLAN_NAME |& tee tf_plan_command.output
        env:
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
          MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_API_KEY }}
          MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_API_KEY }}
          TF_VAR_resource_group_name_tfstate: ${{ vars.TF_VAR_resource_group_name_tfstate }}
          TF_VAR_storage_account_name_tfstate: ${{ vars.TF_VAR_storage_account_name_tfstate }}
          TF_VAR_container_name_tfstate: ${{ vars.TF_VAR_container_name_tfstate }}
          TF_VAR_mongo_atlas_client_id: ${{ secrets.TF_VAR_mongo_atlas_client_id }}
          TF_VAR_mongo_atlas_client_secret: ${{ secrets.TF_VAR_mongo_atlas_client_secret }}
          TF_VAR_org_id: ${{ secrets.TF_VAR_org_id }}
          TF_VAR_cluster_name: ${{ vars.TF_VAR_cluster_name }}
          TF_VAR_project_name: ${{ vars.TF_VAR_project_name }}
          TF_VAR_key_name_tfstate: ${{ vars.TF_VAR_key_name_tfstate }}
          TF_VAR_key_name_infra_tfstate: ${{ vars.TF_VAR_key_name_infra_tfstate }}
          TF_VAR_open_access: ${{ vars.TF_VAR_open_access }}

      - name: Post plan comment
        uses: GetTerminus/terraform-pr-commenter@7f94331232e2a9c9e94c80316e6dcd683aeaf0a4 # v3.0.3
        if: ${{ !cancelled() && github.event_name == 'pull_request' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_WORKSPACE: ${{ inputs.working_directory }}
        with:
          commenter_type: plan
          commenter_plan_path: ${{inputs.working_directory}}/tf_plan_command.output
          commenter_exitcode: ${{ steps.plan.outputs.exitcode }}

      - name: Archive terraform plan
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{env.TF_PLAN_NAME}}
          path: ${{inputs.working_directory}}/${{env.TF_PLAN_NAME}}

      - name: Parse terraform plan to JSON
        run: terraform show -json $TF_PLAN_NAME > $TF_PLAN_NAME.json

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: [validate, plan]
    if: ${{ success() && inputs.apply_changes == true }}

    permissions:
      issues: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Await Manual Approval
        uses: trstringer/manual-approval@74d99dff7380e3e4b122d4ededcbca2b6ce59367 # v1.12.0
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: githubUsername1,githubUsername2 # replace with actual GitHub usernames
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Terraform Apply"
          issue-body: "Please approve or deny the deployment."

  apply:
    name: Apply
    needs: [validate, plan, manual-approval]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    env:
      TF_PLAN_NAME: ${{ needs.plan.outputs.tf_plan_name }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: 'Checkout'
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: 'Azure CLI login'
        uses: azure/login@6b2456866fc08b011acb422a92a4aa20e2c4de32 # v2.1.0
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
          allow-no-subscriptions: false

      - name: Download a single artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ env.TF_PLAN_NAME }}
          path: ${{ inputs.working_directory }}

      - name: Write backend config file
        run: |
          cat > backend.tfbackend <<EOF
          resource_group_name  = "${{ env.TF_VAR_resource_group_name_tfstate }}"
          storage_account_name = "${{ env.TF_VAR_storage_account_name_tfstate }}"
          container_name       = "${{ env.TF_VAR_container_name_tfstate }}"
          key                  = "${{ inputs.area }}.tfstate"
          use_oidc             = true
          EOF
        env:
          TF_VAR_resource_group_name_tfstate: ${{ vars.TF_VAR_resource_group_name_tfstate }}
          TF_VAR_storage_account_name_tfstate: ${{ vars.TF_VAR_storage_account_name_tfstate }}
          TF_VAR_container_name_tfstate: ${{ vars.TF_VAR_container_name_tfstate }}

      - name: Terraform init
        run: terraform init -backend-config=backend.tfbackend

      - name: Terraform apply
        run: terraform apply -auto-approve ${{ env.TF_PLAN_NAME }}
        env:
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
          MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_API_KEY }}
          MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_API_KEY }}
          TF_VAR_mongo_atlas_client_id: ${{ secrets.TF_VAR_mongo_atlas_client_id }}
          TF_VAR_mongo_atlas_client_secret: ${{ secrets.TF_VAR_mongo_atlas_client_secret }}
          TF_VAR_org_id: ${{ secrets.TF_VAR_org_id }}
          TF_VAR_cluster_name: ${{ vars.TF_VAR_cluster_name }}
          TF_VAR_project_name: ${{ vars.TF_VAR_project_name }}
          TF_VAR_resource_group_name_tfstate: ${{ vars.TF_VAR_resource_group_name_tfstate }}
          TF_VAR_storage_account_name_tfstate: ${{ vars.TF_VAR_storage_account_name_tfstate }}
          TF_VAR_container_name_tfstate: ${{ vars.TF_VAR_container_name_tfstate }}
          TF_VAR_key_name_tfstate: ${{ vars.TF_VAR_key_name_tfstate }}
          TF_VAR_key_name_infra_tfstate: ${{ vars.TF_VAR_key_name_infra_tfstate }}
          TF_VAR_open_access: ${{ vars.TF_VAR_open_access }}
